language: haxe

os:
  - linux
  - osx

dist: bionic

haxe:
  - "4.1.2"
  - development

matrix:
  allow_failures:
    - haxe: development

install:
  - haxelib install all --always
  - haxelib list

script:
  - haxe server.hxml
  - haxe web.hxml
  - haxe web-mp.hxml
  - haxe flash.hxml

deploy:
  provider: script
  script: haxe deploy.hxml
  on:
    branch: master
    haxe: "4.1.2"
    condition: $TRAVIS_OS_NAME = linux && $TRAVIS_EVENT_TYPE != "cron"
  skip_cleanup: true
