language: haxe

os:
  - linux
  - osx

dist: xenial

haxe:
  - "3.4.7"
  - "4.0.0-rc.2"
  - development

matrix:
  allow_failures:
    - haxe: development

hxml:
  - server.hxml
  - web.hxml
  - flash.hxml

deploy:
  provider: script
  script: haxe deploy.hxml
  on:
    branch: master
    haxe: "3.4.7"
    condition: $TRAVIS_OS_NAME = linux && $TRAVIS_EVENT_TYPE != "cron"
  skip_cleanup: true
